version: "3.8"

services:
  # Databases
  mssqldb:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssqldb
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA}
      MSSQL_DB: ${MSSQL_DB}
      MSSQL_USER: ${MSSQL_U}
      MSSQL_PASSWORD: ${MSSQL_PWD}
    ports:
      - "1433:1433"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MG_DB}
    ports:
      - "27018:27017"

  # Services
  medilabo-gateway:
    build:
      context: ./medilabo-gateway
      dockerfile: Dockerfile
    image: medilabo-gateway:latest
    ports:
      - "9000:9000"

  medilabo-patients:
    depends_on:
      - mssqldb
    build:
      context: ./medilabo-patients
      dockerfile: Dockerfile
    image: medilabo-patient:latest
    container_name: medilabo-patients
    ports:
      - "9001:9001"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssqldb:1433;encrypt=false;database=${MSSQL_DB}
      SPRING_DATASOURCE_USERNAME: ${MSSQL_U}
      SPRING_DATASOURCE_PASSWORD: ${MSSQL_PWD}

  medilabo-notes:
    depends_on:
      - mongodb
    build:
      context: ./medilabo-notes
      dockerfile: Dockerfile
    image: medilabo-notes:latest
    container_name: medilabo-notes
    ports:
      - "9002:9002"
    restart: on-failure
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: ${MG_DB}

  medilabo-assessments:
    depends_on:
      - medilabo-gateway
      - medilabo-patients
      - medilabo-notes
    build:
      context: ./medilabo-assessments
      dockerfile: Dockerfile
    image: medilabo-assessments:latest
    container_name: medilabo-assessments
    ports:
      - "9003:9003"
    restart: on-failure
    environment:
      MEDILABO_PATIENTS_URL: http://medilabo-gateway:9000/medilabo-patients
      MEDILABO_NOTES_URL: http://medilabo-gateway:9000/medilabo-notes

  medilabo-frontend:
    depends_on:
      - medilabo-gateway
      - medilabo-patients
      - medilabo-notes
      - medilabo-assessments
    build:
      context: ./medilabo-frontend
      dockerfile: Dockerfile
    image: medilabo-frontend:latest
    container_name: medilabo-frontend
    ports:
      - "4200:4200"
    restart: "no"
    environment:
      MEDILABO_GATEWAY_URL: http://medilabo-gateway:9000

