server:
  port: 9002

spring:
  application:
    name: "notes-service"
  security:
    basic:
      enabled: true
    user:
      name: "admin"
      password: "medilabo"
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_PORT}
      database: ${SPRING_DATA_MONGODB_DATABASE}