server:
  port: 9002

spring:
  application:
    name: "notes-service"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ML_Notes_OC
  security:
    basic:
      enabled: true
    user:
      name: ${APP_U}
      password: ${APP_PWD}