server:
  port: 9000

spring:
  application:
    name: "gateway-service"
  cloud:
    gateway:
      routes:
        - id: patients-service
          uri: http://localhost:9001
          predicates:
            - Path=/patients/**
#          filters:
#            - SetPath=/patients/        # Same as controller @RequestMapping
        - id: notes_route
          uri: http://localhost:9002
          predicates:
            - Path=/notes-service/**
          filters:
            - SetPath=/notes/
        - id: assessments_route
          uri: http://localhost:9003
          predicates:
            - Path=/assessments-service/**
          filters:
            - SetPath=/assessments/
        - id: angular_route
          uri: http://localhost:4200/
          predicates:
            - Path=/**