server:
  port: 9000

spring:
  application:
    name: "gateway-service"
  cloud:
    gateway:
      globalcors:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"
      routes:
        - id: patients-service
          uri: http://medilabo-patients:9001
          predicates:
            - Path=/patients/**
        - id: notes-service
          uri: http://medilabo-notes:9002
          predicates:
            - Path=/notes/**
        - id: assessments-service
          uri: http://medilabo-assessments:9003
          predicates:
            - Path=/assessments/**
        - id: front-service
          uri: http://medilabo-frontend:4200/
          predicates:
            - Path=/**