server:
  port: 9000

spring:
  application:
    name: "gateway-service"
  cloud:
    gateway:
      globalcors:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"
      routes:
        - id: patients-service
          uri: http://localhost:9001
          predicates:
            - Path=/patients/**
        #          filters:
        #            - SetPath=/patients/        # Same as controller @RequestMapping
        - id: notes-service
          uri: http://localhost:9002
          predicates:
            - Path=/notes-service/**
          filters:
            - SetPath=/notes/
        - id: assessments-service
          uri: http://localhost:9003
          predicates:
            - Path=/assessments-service/**
          filters:
            - SetPath=/assessments/
        - id: front-service
          uri: http://localhost:4200/
          predicates:
            - Path=/**