server:
  port: 9000

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: "gateway-service"
  cloud:
    gateway:
      globalcors:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"
      routes:
        - id: patients-service
          uri: http://localhost:9001
          predicates:
            - Path=/patients/**
        - id: notes-service
          uri: http://localhost:9002
          predicates:
            - Path=/notes/**
        - id: assessments-service
          uri: http://localhost:9003
          predicates:
            - Path=/assessments/**
        - id: front-service
          uri: http://localhost:4200/
          predicates:
            - Path=/**