server:
  port: 9000

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: "gateway-service"
  security:
    basic:
      enabled: true
    user:
      name: "admin"
      password: "medilabo"
  cloud:
    gateway:
      globalcors:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"
      routes:
        - id: patients-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/patients/**
        - id: notes-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/notes/**
        - id: assessments-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/assessments/**
        - id: front-service
          uri: http://localhost:4200/
          predicates:
            - Path=/**