server:
  port: 9003

spring:
  application:
    name: "assessments-service"
  security:
    basic:
      enabled: true
    user:
      name: "admin"
      password: "medilabo"

logging:
  level:
    org.springframework.context.annotation.ClassPathBeanDefinitionScanner: DEBUG